name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout do repositório
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Instalar dependências e Cypress
        run: npm ci

      - name: 🔧 Instalar binário do Cypress
        run: npx cypress install

      - name: 🧪 Executar testes Cypress
        run: npx cypress run